# Equal-Weight S&P 500 Index Fund

## Introduction & Library Imports

The S&P 500 is the world's most popular stock market index. The largest fund that is benchmarked to this index is the SPDR® S&P 500® ETF Trust. It has more than US$250 billion of assets under management.

The goal of this section of the course is to create a Python script that will accept the value of your portfolio and tell you how many shares of each S&P 500 constituent you should purchase to get an equal-weight version of the index fund.

## Library Imports

The first thing we need to do is import the open-source software libraries that we'll be using in this tutorial.

In [1]:
# Speed up calculations through modules written in a faster language
import numpy as np
# Panel data: makes it easier to work with data that has multiple dimensions
import pandas as pd
# Gold standard for making HTTP requests
import requests
# Make it easier to save formatted Excel files from Python scripts
import xlsxwriter
# Provides basic mathematical functions
import math
# Help handle streams (sequences of data)
import io

## Importing Our List of Stocks

The next thing we need to do is import the constituents of the S&P 500.

These constituents change over time, so in an ideal world you would connect directly to the index provider (Standard & Poor's) and pull their real-time constituents on a regular basis.

Paying for access to the index provider's API is outside of the scope of this course. 

There's a static version of the S&P 500 constituents available here. [Click this link to download them now](https://drive.google.com/file/d/1ZJSpbY69DVckVZlO9cC6KkgfSufybcHN/view?usp=sharing). Move this file into the `starter-files` folder so it can be accessed by other files in that directory.

Now it's time to import these stocks to our Jupyter Notebook file.

In [2]:
# Save S&P 500 stocks to a Pandas DataFrame

# Create a identifiable client using a user-agent to avoid being detected as a bot
url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
headers = {
    "User-Agent": "Mozilla/5.0"
}

# Make a GET request to the URL and read the HTML content
response = requests.get(url, headers=headers)
# Use io.StringIO to treat the response text like a file object
tables = pd.read_html(io.StringIO(response.text))
# Retrieve the ticker symbols of the S&P 500 companies from the first table on the page
stocks = tables[0]["Symbol"]

## Acquiring an API Token

Now it's time to import our IEX Cloud API token. This is the data provider that we will be using throughout this course.

API tokens (and other sensitive information) should be stored in a `secrets.py` file that doesn't get pushed to your local Git repository. We'll be using a sandbox API token in this course, which means that the data we'll use is randomly-generated and (more importantly) has no cost associated with it.

[Click here](http://nickmccullum.com/algorithmic-trading-python/secrets.py) to download your `secrets.py` file. Move the file into the same directory as this Jupyter Notebook before proceeding.

In [3]:
# [Deprecated - Yahoo Finance API Replacement]

# Use yfinance as the API to retrieve stock data on the S&P 500 companies
import yfinance as yf

## Making Our First API Call

Now it's time to structure our API calls to IEX cloud. 

We need the following information from the API:

* Market capitalization for each stock
* Price of each stock

In [4]:
symbol = "AAPL"

data = yf.Ticker(symbol)
data.info

{'address1': 'One Apple Park Way',
 'city': 'Cupertino',
 'state': 'CA',
 'zip': '95014',
 'country': 'United States',
 'phone': '(408) 996-1010',
 'website': 'https://www.apple.com',
 'industry': 'Consumer Electronics',
 'industryKey': 'consumer-electronics',
 'industryDisp': 'Consumer Electronics',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple Vision Pro, Apple TV, Apple Watch, Beats products, and HomePod, as well as Apple branded and third-party accessories. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts, as well as advertising services include third-party licensing arrangements and its own advertising platforms. In addition, the company offers various subscription-based services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV, which offers exclusive original content and live sports; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers and resellers. The company was formerly known as Apple Computer, Inc. and changed its name to Apple Inc. in January 2007. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.',
 'fullTimeEmployees': 150000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Timothy D. Cook',
   'age': 64,
   'title': 'CEO & Director',
   'yearBorn': 1961,
   'fiscalYear': 2025,
   'totalPay': 16759518,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Kevan  Parekh',
   'age': 53,
   'title': 'Senior VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 4034174,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Sabih  Khan',
   'age': 58,
   'title': 'Senior VP & Chief Operating Officer',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5021905,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': "Ms. Deirdre  O'Brien",
   'age': 58,
   'title': 'Senior Vice President of Retail & People',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5037867,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ben  Borders',
   'age': 44,
   'title': 'Principal Accounting Officer',
   'yearBorn': 1981,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Suhasini  Chandramouli',
   'title': 'Director of Investor Relations',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Jennifer G. Newstead J.D.',
   'age': 54,
   'title': 'Senior VP & General Counsel',
   'yearBorn': 1971,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Kristin Huguet Quayle',
   'title': 'Vice President of Worldwide Communications',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Greg  Joswiak',
   'title': 'Senior Vice President of Worldwide Marketing',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Adrian  Perica',
   'age': 51,
   'title': 'Vice President of Corporate Development',
   'yearBorn': 1974,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 2,
 'boardRisk': 1,
 'compensationRisk': 7,
 'shareHolderRightsRisk': 1,
 'overallRisk': 1,
 'governanceEpochDate': 1772323200,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://investor.apple.com/',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 260.81,
 'open': 258.66,
 'dayLow': 254.18,
 'dayHigh': 258.95,
 'regularMarketPreviousClose': 260.81,
 'regularMarketOpen': 258.66,
 'regularMarketDayLow': 254.18,
 'regularMarketDayHigh': 258.95,
 'dividendRate': 1.04,
 'dividendYield': 0.4,
 'exDividendDate': 1770595200,
 'payoutRatio': 0.1304,
 'fiveYearAvgDividendYield': 0.52,
 'beta': 1.116,
 'trailingPE': 32.374683,
 'forwardPE': 27.513294,
 'volume': 40132517,
 'regularMarketVolume': 40132517,
 'averageVolume': 48273077,
 'averageVolume10days': 41063120,
 'averageDailyVolume10Day': 41063120,
 'bid': 255.52,
 'ask': 256.01,
 'bidSize': 1,
 'askSize': 2,
 'marketCap': 3759141289984,
 'nonDilutedMarketCap': 3828988123400,
 'fiftyTwoWeekLow': 169.21,
 'fiftyTwoWeekHigh': 288.62,
 'allTimeHigh': 288.62,
 'allTimeLow': 0.049107,
 'priceToSalesTrailing12Months': 8.629464,
 'fiftyDayAverage': 263.5268,
 'twoHundredDayAverage': 245.0323,
 'trailingAnnualDividendRate': 1.03,
 'trailingAnnualDividendYield': 0.003949235,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 3852590120960,
 'profitMargins': 0.27037,
 'floatShares': 14656182062,
 'sharesOutstanding': 14681140000,
 'sharesShort': 129553812,
 'sharesShortPriorMonth': 116854414,
 'sharesShortPreviousMonthDate': 1769731200,
 'dateShortInterest': 1772150400,
 'sharesPercentSharesOut': 0.0088,
 'heldPercentInsiders': 0.01637,
 'heldPercentInstitutions': 0.65213996,
 'shortRatio': 2.41,
 'shortPercentOfFloat': 0.0088,
 'impliedSharesOutstanding': 14697926000,
 'bookValue': 5.998,
 'priceToBook': 42.640877,
 'lastFiscalYearEnd': 1758931200,
 'nextFiscalYearEnd': 1790467200,
 'mostRecentQuarter': 1766793600,
 'earningsQuarterlyGrowth': 0.159,
 'netIncomeToCommon': 117776998400,
 'trailingEps': 7.9,
 'forwardEps': 9.29587,
 'lastSplitFactor': '4:1',
 'lastSplitDate': 1598832000,
 'enterpriseToRevenue': 8.844,
 'enterpriseToEbitda': 25.196,
 '52WeekChange': 0.24384773,
 'SandP52WeekChange': 0.22716212,
 'lastDividendValue': 0.26,
 'lastDividendDate': 1770595200,
 'quoteType': 'EQUITY',
 'currentPrice': 255.76,
 'targetHighPrice': 350.0,
 'targetLowPrice': 205.0,
 'targetMeanPrice': 295.43536,
 'targetMedianPrice': 300.0,
 'recommendationMean': 1.89583,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 41,
 'totalCash': 66907000832,
 'totalCashPerShare': 4.557,
 'ebitda': 152901992448,
 'totalDebt': 90509000704,
 'quickRatio': 0.845,
 'currentRatio': 0.974,
 'totalRevenue': 435617005568,
 'debtToEquity': 102.63,
 'revenuePerShare': 29.305,
 'returnOnAssets': 0.24377,
 'returnOnEquity': 1.5202099,
 'grossProfits': 206157004800,
 'freeCashflow': 106312753152,
 'operatingCashflow': 135471996928,
 'earningsGrowth': 0.183,
 'revenueGrowth': 0.157,
 'grossMargins': 0.47325,
 'ebitdaMargins': 0.35099998,
 'operatingMargins': 0.35374,
 'financialCurrency': 'USD',
 'symbol': 'AAPL',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'corporateActions': [],
 'postMarketTime': 1773348265,
 'regularMarketTime': 1773345602,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_24937',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'regularMarketChangePercent': -1.9362767,
 'regularMarketPrice': 255.76,
 'marketState': 'POST',
 'shortName': 'Apple Inc.',
 'longName': 'Apple Inc.',
 'postMarketPrice': 256.1232,
 'postMarketChange': 0.36320496,
 'regularMarketChange': -5.050003,
 'regularMarketDayRange': '254.18 - 258.95',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 48273077,
 'fiftyTwoWeekLowChange': 86.54999,
 'fiftyTwoWeekLowChangePercent': 0.5114945,
 'fiftyTwoWeekRange': '169.21 - 288.62',
 'fiftyTwoWeekHighChange': -32.86,
 'fiftyTwoWeekHighChangePercent': -0.11385213,
 'fiftyTwoWeekChangePercent': 24.384773,
 'dividendDate': 1770854400,
 'earningsTimestamp': 1769720400,
 'earningsTimestampStart': 1777579200,
 'earningsTimestampEnd': 1777579200,
 'earningsCallTimestampStart': 1769724000,
 'earningsCallTimestampEnd': 1769724000,
 'isEarningsDateEstimate': True,
 'epsTrailingTwelveMonths': 7.9,
 'epsForward': 9.29587,
 'epsCurrentYear': 8.51089,
 'priceEpsCurrentYear': 30.05091,
 'fiftyDayAverageChange': -7.7668,
 'fiftyDayAverageChangePercent': -0.029472524,
 'twoHundredDayAverageChange': 10.727692,
 'twoHundredDayAverageChangePercent': 0.043780725,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '1.9 - Buy',
 'cryptoTradeable': False,
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 345479400000,
 'postMarketChangePercent': 0.14201008,
 'displayName': 'Apple',
 'trailingPegRatio': 2.3344}

## Parsing Our API Call

The API call that we executed in the last code block contains all of the information required to build our equal-weight S&P 500 strategy. 

With that said, the data isn't in a proper format yet. We need to parse it first.

In [5]:
price = data.info.get("currentPrice", "N/A")
market_cap = data.info.get("marketCap", "N/A")

## Adding Our Stocks Data to a Pandas DataFrame

The next thing we need to do is add our stock's price and market capitalization to a pandas DataFrame. Think of a DataFrame like the Python version of a spreadsheet. It stores tabular data.

In [6]:
# Specify columns for the DataFrame
my_columns = ["Ticker", "Stock Price", "Market Capitialization", "Number of Shares to Buy"]
final_dataframe = pd.DataFrame(columns = my_columns)
final_dataframe

Empty DataFrame
Columns: [Ticker, Stock Price, Market Capitialization, Number of Shares to Buy]
Index: []

In [7]:
# Append the stock data to the DataFrame

pd.concat([
    final_dataframe,
    pd.DataFrame(
        [[
            symbol,
            price,
            market_cap,
            "N/A"
        ]],
        # Specify which columns to join the data to
        columns = my_columns
    )],
# Create new index starting from 0
ignore_index = True
)

  Ticker Stock Price Market Capitialization Number of Shares to Buy
0   AAPL      255.76          3759141289984                     N/A

## Looping Through The Tickers in Our List of Stocks

Using the same logic that we outlined above, we can pull data for all S&P 500 stocks and store their data in the DataFrame using a `for` loop.

In [8]:
final_dataframe = pd.DataFrame(columns = my_columns)
# Limit to first five stocks to avoid slow API calls
for symbol in stocks[:5]:
    data = yf.Ticker(symbol)

    final_dataframe = pd.concat([
    final_dataframe,
    pd.DataFrame(
        [[
            symbol,
            data.info.get("currentPrice", "N/A"),
            data.info.get("marketCap", "N/A"),
            "N/A"
        ]],
        # Specify which columns to join the data to
        columns = my_columns
    )],
    # Create new index starting from 0
    ignore_index = True
    )

In [9]:
final_dataframe

  Ticker Stock Price Market Capitialization Number of Shares to Buy
0    MMM       149.1            78530969600                     N/A
1    AOS       66.57             9205959680                     N/A
2    ABT      108.14           187913027584                     N/A
3   ABBV      225.37           398492237824                     N/A
4    ACN      196.05           121578225664                     N/A

## Using Batch API Calls to Improve Performance

Batch API calls are one of the easiest ways to improve the performance of your code.

This is because HTTP requests are typically one of the slowest components of a script.

Also, API providers will often give you discounted rates for using batch API calls since they are easier for the API provider to respond to.

IEX Cloud limits their batch API calls to 100 tickers per request. Still, this reduces the number of API calls we'll make in this section from 500 to 5 - huge improvement! In this section, we'll split our list of stocks into groups of 100 and then make a batch API call for each group.

## Calculating the Number of Shares to Buy

As you can see in the DataFrame above, we stil haven't calculated the number of shares of each stock to buy.

We'll do that next.

## Formatting Our Excel Output

We will be using the XlsxWriter library for Python to create nicely-formatted Excel files.

XlsxWriter is an excellent package and offers tons of customization. However, the tradeoff for this is that the library can seem very complicated to new users. Accordingly, this section will be fairly long because I want to do a good job of explaining how XlsxWriter works.

### Initializing our XlsxWriter Object

### Creating the Formats We'll Need For Our `.xlsx` File

Formats include colors, fonts, and also symbols like `%` and `$`. We'll need four main formats for our Excel document:
* String format for tickers
* \\$XX.XX format for stock prices
* \\$XX,XXX format for market capitalization
* Integer format for the number of shares to purchase

### Applying the Formats to the Columns of Our `.xlsx` File

We can use the `set_column` method applied to the `writer.sheets['Recommended Trades']` object to apply formats to specific columns of our spreadsheets.

Here's an example:

```python
writer.sheets['Recommended Trades'].set_column('B:B', #This tells the method to apply the format to column B
                     18, #This tells the method to apply a column width of 18 pixels
                     string_template #This applies the format 'string_template' to the column
                    )
```

This code works, but it violates the software principle of "Don't Repeat Yourself". 

Let's simplify this by putting it in 2 loops:

## Saving Our Excel Output

Saving our Excel file is very easy: